# Generated by Django 5.0.7 on 2024-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PostID', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('Content', models.TextField()),
                ('Date_posted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Content', models.TextField()),
                ('Category', models.TextField()),
                ('Date_Published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
            ],
        ),
    ]
